package com.BookMyShow.models;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Data
@Table(name = "theaters")
@NoArgsConstructor
@AllArgsConstructor
public class Theater {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer theaterId;

    private String theaterName;

    private String address;

    private Integer numberOfScreens;

    @OneToMany(mappedBy = "theater", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Show> showList = new ArrayList<>();

    @OneToMany(mappedBy = "theater", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<TheaterSeat> theaterSeatList = new ArrayList<>();

    @ManyToMany(mappedBy = "theaterList", fetch = FetchType.LAZY)
    private List<Movie> movies = new ArrayList<>();

    // Constructors, getters, setters are generated by Lombok's @Data


}
